gems:
  - bourbon
  - neat
  - octopress-autoprefixer

# Structure configuration
source: source
destination: build

assets:
  cachebust: soft

# Site settings
title: Legumbres Marcos
description: Legumbres Marcos.

# Name of project on Github
baseurl: 

# Build settings
markdown: kramdown
